### PR TITLE
7.7.+

### PR DESCRIPTION
**Pull request by xecrets**
Hi,

Here are the promised fixes to the translation project to handle high load both with and without load balancing. There are also a few fixes to ensure Dispose() of the WebResponse objects in the Bing-translation code, preventing exhaustion of outgoing web connections.

I have aimed at changing as little as possible, and also to keep it as simple as possible. While simple Monitor.Enter() based locks can be optimized, I'm refraining from this in the interest of simplicity and correctness. If actual lock contention can be shown in the real world, this can be optimized then.

Best regards,

Svante

### CODE REVIEW

**Comment by jstemerdink** [comment]
Hi, thanx. I have a few questions though.
Am not sure what you mean with MissingValues causing an exception when indexing? This is just a helper that you could use on a view for the item, to show what values for languages enabled for the site are missing. So there should be a StartPage available.
I also don't quite get why you would want to use the CacheManager to "store" the provider? This way the values are reloaded every time you publish a content item. That is why the custom event was there, so only when a translation related item is changed the values are reloaded.
I also wonder why you removed the double-checked locking in the TranslationFactory singleton (that's what the volatile was for), as a "normal" singleton is not thread safe.

**Comment by xecrets** [comment]
Hi!

I'll try to answer below.

" MissingValues causing an exception when indexing? This is just a helper
that you could use on a view for the item, to show what values for
languages enabled for the site are missing. So there should be a StartPage
available."

_\- The thing is there isn't a StartPage available during indexing. The
indexing code is started without a request and without a HttpContext. The
property *is_ called during indexing, and _does_ cause an exception due to
StartPage == null :-(. I don't recall exactly the stack trace, and just how
it got there - but I'm very sure it did, and the change resolves the issue.
But you're right, just looking at the code there seems to be no reason for
it to be called.*

"I also don't quite get why you would want to use the CacheManager to
"store" the provider? This way the values are reloaded every time you
publish a content item. That is why the custom event was there, so only
when a translation related item is changed the values are reloaded_._"

_\-  The provider is still only reloaded when a content item that is a
Translation-related page is changed or deleted. The idea with using the
CacheManger to store the provider in the CacheManager is to keep things
simple and reasonably efficient. Note that the CacheManager is load
balancing aware, and will handle the invalidation without any effort on our
part The only difference between the strategy before, is that the
translation data is reloaded in all of the load-balancing members
(including the one where the publish is performed). This case was optimized
previously, but it actually caused a *lot_ more pain than the benefits it
gained. First of all, it totally did not work in a load balancing
environment. Second, the code handling the deletion was wrong - it never
got deleted locally. Third, there were numerous race conditions just
locally. Reloading the translation tree is also likely not a very heavy
operation, since the EPiServer cache is likely to have all or most of it
anyway. It's simply too complex to keep yet another shadow copy of the
translation tree in memory and to try to keep it in sync. There were
various race conditions there as well, even in a single server scenario.
Specifically, the 'reload provider' could easily be called several times if
requests were coming in fast. This is now resolved with a simple lock on
the 'LocalizationProvider' property. Also, you tried to fix some of the
race conditions with the very complicated retry loop. All this complexity
disappeared by the simple expediency of simply reloading the translations
when a translation is changed - note that this had to be done in the other
load balancing members (if any) anyway, so the optimization can at most
benefit a single-server site slightly. But, as mentioned, it just gets too
complex and simply will not be correct under load.*

"I also wonder why you removed the double-checked locking in the
TranslationFactory singleton (that's what the volatile was for), as a
"normal" singleton is not thread safe."

_\- Double-checking is simply not worth the effort and is possibly
counterproductive. By introducing the volatile you do ensure that the
double-check actually works, but you're also telling the compiler instruct
the processor to stop all parallel pipeline and reordering optimizations,
effectively causing a synchronization point in the code execution. Whether
this actually anyway is faster than the simple lock is almost
philosophical. My view is that it's simply too much complexity (really -
how many C# programmers really understand 'volatile'? I'm not sure I do
without peeking at the C# reference.) for way too litlle potential gain
(and I'm not even sure there will be a gain!). The simple lock I replaced
it with is effective, works, is easy to understand - and if you ever see
lock contention there, it can be fixed then. The 'Instance' property is not
very likely to be called frequently, and to optimize that by introducing
complexity when a simple lock works is I believe unnecessary._

In general, doing thread-safe code is such a difficult task, that I'll
always opt for simplicity and safety in the areas of contention to start
with. Only if I see any actual signs of measurable poor performance will I
try to optimize. I have too much respect for the challenges of making
dead-lock free, and race condition-free thread-safe code to opt for
complexity in the name of effiency I am not certain I'll need. It's a bit
like the old Rolls Royce specification of motor effect - "sufficient". If
the performance of the site is "sufficient", I will not try to optimize it
further. This is not at all the same as writing inefficient code, it's
about writing sufficiently efficient code, and avoid trading unneeded
effiency for complexity. I'd rather have it do the right thing, _every_
time, regardless of load and perform satisfyingly, than have it perform at
blistering speed - but only get it it right 99% of the time.

I'd be happy to talk a bit over Skype for example if you'd like to discuss
it further.

For what it's worth - it's been working over a week now in a load balancing
environment with medium load, and it's been working perfectly. The site in
question has been having problems due to these issues since the start 6
months ago, and all these seem to have disappeared now.

Best regards,

Svante

**Comment by jstemerdink** [comment]
Hi Svante,
A thought about the missing values throwing an exception during indexing? Are you using EPiServer Find? I added a JsonIgnore attribute to prevent find from indexing the extra properties, just in case. 

Using the CacheManager to store a provider that in itself delivers cached content just does not feel right. Maybe it's me, but I'll run this concept by some others. It is advised though to take a dependency on ISynchronizedObjectInstanceCache instead of using the CacheManager as from 7.5. BTW, the CacheManager uses the exact same methods to invalidate the cache as I did, using an event and raiser id. So the events should trigger across all load balanced machines.

About the double checked locking, I guess it is a matter of opinion. As you say for the simpler lock, you could always change it, if it proves to be not functioning well.

Anyway. Your performance problems and the CacheManager fix was bugging me, so I decided to rethink and rewrite the complete provider. I decided to use the Memory Provider instead, which was not available in 6, I think, where my original version started. This provider does not need to be reloaded to load new content and can be kept in memory. It provides methods for adding and removing content, etc. This gave a way better performance.
Instead of a simple lock around the reload of the content, I chose to implement a read/write lock, which gave a huge performance boost. Though I'm thinking about maybe using PostSharp for this , their Reader-Writer Synchronized pattern, which would remove a lot of code. They also have an aspect to detect and log deadlocks at runtime (http://doc.postsharp.net/deadlock-detection), which might prove useful.
I also refactored all the older ways of doing things to injecting the necessary services, EPiServer style.

You can find it over here: https://github.com/jstemerdink/EPi.Libraries.Temp

Please let me know what you think and if this holds up to your performance tests? 

If you have any pull requests, please use seperate commits, as it will be easier to merge.

Best,
Jeroen

**Comment by xecrets** [comment]
Hello!

The CacheManager is nothing magic we need to be wary of or especially
careful with. It just keeps a reference to an object around in a handy
fashion, it doesn't even guarantee to keep it  around. The object that I'm
suggesting to keep there is also a pretty straightforward object, it does
nothing strange. Also, please note that the whole point is to not keep the
provider instance that EPiServer is told about there - that is stable, as
opposed to the original solution where it was removed and added repeatedly
which is one of the race conditions that needed fixing, and this stragety
fixes. The wrapper is only registered once, and it's kept there.
Internally, however, it uses the CacheManager to keep another instance
around, and if it's not around, instantiate a new one.

If you'd like to discuss the use of the CacheManager like this I welcome it
- it's a good use of it. I should also perhaps mention that one reason that
  I'm comfortable with this is that I was working at EPiServer when much of
  the loadbalancing strategies including remote events were originally
  implemented, and in fact am co-designer of much of the back-end parts of
  EPiServer in version 5, much of which is still more or less intact.

You're of course essentially right in that pretty much the same thing
happens with your custom event solution, as with using CacheManager to
handle it - the difference is that we don't need to know, or code it. I'm
not saying your custom events did not work, I'm saying there is no need to
roll your own. EPiServer just promises to make it work without further
effort from our side, and we're automatically kept uptodate with future
advances, as well as smarter cache implementations. A CacheManager
implementation that implements a shared cache could probably be leveraged
without any changes at all - it just works. Since caching and load
balancing is complex, I try to avoid to work directly with it and instead
rely on mechanisms present in the platform.

Also, there were some definite issues that you tried to work around, all
that complicated "let's try again" code just disappeared and it's been
working without a hitch in a production environment for two weeks now.

Using ISynchronizedObjectInstanceCache is probably better, I missed when
they obsoleted CacheManager as a wrapper - I would have expected that they
would re-implement that to use the configured injected dependency, but
whatever. You're right, if that's the recommendation, that's how it should
be done. Thanks for pointing that out.

I'll try to get some time to look at your new solution next week, however,
this along with your wish for smaller commits brings up another
suggestion/wish list from me.

The problem I was faced with when working with the code from the repository
was that it was not one library, it was seven or something. And I could not
get it to build, partially because of a few mistakes in the checked in
stuff, and partially because of lacking dependencies such as PostSharp. (I
installed that, and I'm kind of regretting it. It messed up my Visual
Studio. It's also a for-pay component, although you may only be using the
free parts)?

Also, we had some custom changes to your code that I needed to retain (I
would have liked to integrate them in your code, or change our code not to
need them, but I was lacking time). Anyway, what I had to do in the end was:
- Manually merge your new code with our version, retaining our mods. Now it
  built and I could test.
- Do the changes.
- Manually merge the updated code back to your repository minus our mods.
- Commit. That's why it was a single commit. I did try to change as little
  as possible, to facilitate the merge.

It would be much easier to contribute if each library was separate and
independent. As a consumer of your code, we're never likely to use all the
code in your Library repository, but one or two components. As long as
there's a working binary dependency that's not an issue, but just about all
the time we end up bringing in the source code in one way or another, and
then we just want the parts that we're using.

If the code in turn depends on third party components and products, that
makes it even less likely that we'll see the benefit in using it.

Of course, there are advantages to using things like PostSharp, I just want
to point out that you're raising the bar for re-use. We may be wrong when
this causes us to hesitate, but I think we're pretty typical. I also try to
keep the number of dependencies as low as possible, and one reason for
_not_ bringing in a specific component is often that it brings along more
dependencies. For example, I'd be very wary of bringing in a component that
uses another DI-container than StructureMap. Not because I love
StructureMap, I don't. In fact I don't like it all - but since EPiServer
uses it, it's there and we just have to live with it. And since it's there,
I don't want another one, even if I feel it's 'better'.

These are just some thoughts, from a frequent user of open source
libraries, as well as the author of a few.

Regardless of which I'd like to say Thank You for the effort going into
your libraries, and for making them available.

Keep in touch! As I said before, I'll be happy to talk over Skype or
something if you'd like to discuss it further.

Regards,

Svante

**Pull request closed without merging**
